export const TYPES = {
  MusicBot: Symbol("MusicBot"),
  Logger: Symbol("Logger"),
  DiscordClient: Symbol("DiscordClient"),
  CommandsHandler: Symbol("CommandsHandler"),
  GuildQueueService: Symbol("GuildQueueService"),
  SkipCommand: Symbol("SkipCommand"),
  PreviousCommand: Symbol("PreviousCommand"),
  PlayCommand: Symbol("PlayCommand"),
  PlayerService: Symbol("PlayerService"),
  PauseCommand: Symbol("PauseCommand"),
  ResumeCommand: Symbol("ResumeCommand"),
  QueueCommand: Symbol("QueueCommand"),
  NowPlayingCommand: Symbol("NowPlayingCommand"),
  JumpCommand: Symbol("JumpCommand"),
  MoveCommand: Symbol("MoveCommand"),
};
