name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.3
        env:
          DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
          DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}
          DISCORD_ACCESS_TOKEN: ${{secrets.DISCORD_ACCESS_TOKEN}}
          SPOTIFY_CLIENT_ID: ${{secrets.SPOTIFY_CLIENT_ID}}
          SPOTIFY_CLIENT_SECRET: ${{secrets.SPOTIFY_CLIENT_SECRET}}
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          envs: DISCORD_CLIENT_ID,DISCORD_CLIENT_SECRET,DISCORD_ACCESS_TOKEN,SPOTIFY_CLIENT_ID,SPOTIFY_CLIENT_SECRET

          script: |
            cd ~/
            directory="app"
            if [ ! -d "$directory" ]; then
              mkdir "$directory"
            fi

            cd "$directory" || exit 1

            if [ ! -d "overseer-music" ]; then
              git clone git@github.com:overseer-discord/overseer-music.git
              cd overseer-music
              else
              cd overseer-music
              git pull origin main
            fi
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install -g yarn
            yarn run start-droplet
