name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd ~/
            directory="app"
            if [ ! -d "$directory" ]; then
              mkdir "$directory"
            fi

            cd "$directory" || exit 1

            if [ ! -d "overseer-music" ]; then
              git clone git@github.com:overseer-discord/overseer-music.git
              cd overseer-music
              else
              cd overseer-music
              git pull origin main
            fi
            chmod +x deploy.sh
            ./deploy.sh
