name: Build & Test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build & Test
      run: |
        yarn install
        yarn run build
        yarn run test
